apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-and-deploy-apps-smoke-test
  labels:
    tekton.dev/pipeline: build-and-deploy-apps
spec:
  params:
    - name: git-url
      value: >-
        https://github.com/redhat-na-ssa/workshop_performance-monitoring-apps.git
    - name: git-revision
      value: main
    - name: context-dir
      value: code-repo
    - name: registry-url
      value: quay.io
    - name: registry-repo
      value: rafaeltuelho
    - name: target-namespace
      value: user1-staging
    - name: quarkus-app-name
      value: quarkus-app
    - name: micronaut-app-name
      value: micronaut-app
    - name: springboot-app-name
      value: springboot-app
    - name: maven-mirror-url
      value: >-
        http://nexus-sonatype-nexus-service.shared-maven-mirror.svc.cluster.local:8081/repository/maven-public
  pipelineRef:
    name: build-and-deploy-apps
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: shared-workspace-pvc
    - emptyDir: {}
      name: maven-settings
    - emptyDir: {}
      name: image-urls-cm
